### ISSUE TITLE
Problems with STAR alignment of the second sample

### ISSUE THREAD

**Issue by Josemamd13** [Josemamd13/decont#1]
Buenas Tomás,
El script me corría perfecto hasta que he intentado hacer el apartado adicional "Comprueba si la salida ya existe antes de ejecutar un comando. Si existe, muestra un mensaje, omite la operación y continúa." 
Creo haberlo hecho, pero desde entonces solo se me alinea con STAR la primera muestra "C57BL_6NJ" y no la segunda muestra "SPRET_EiJ" y por muchas vueltas y modificaciones que le he hecho, no consigo ver dónde está el fallo... 
Gracias de antemano.

**Comment by tdido** [comment]
Así a simple vista veo que el nombre de la variable en el `if` parece ser incorrecto: `out/star/$sid1/`. Fijate si tiene que ver con eso.
